name: signlinggo
description: "SignLinggo - A Flutter app for learning and communicating with Malaysian Sign Language (BIM)"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'
 # sdk: '>=3.3.0 <4.0.0'
 # sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  image: ^4.1.3

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0

  # Navigation
  go_router: ^14.2.7

  # Local Storage
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  path: ^1.9.1

  # Firebase & Authentication
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.0

  #SupaBase Videos and Pictures
  supabase_flutter: ^2.8.0

  # Media & File Handling
  image_picker: ^1.1.3
  video_player: ^2.8.6
  camera: ^0.11.3
  record: ^6.1.2
  just_audio: ^0.9.36
  audio_waveforms: ^1.1.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0
  audio_session: ^0.1.16 #convo
  #flutter_cache_manager: ^3.3.1 #Learn Page Caching
  vector_math: ^2.1.4  # For fast math operations

  # Networking
  http: ^1.2.2

  # UI & Utils
  flutter_spinkit: ^5.2.1
  visibility_detector: ^0.4.0+2
  share_plus: ^10.0.2
  scroll_to_index: ^3.0.1
  dio: ^5.9.0
  #open_file_plus: ^3.4.1+1
  open_file: ^3.0.0
  archive: ^4.0.7
  cached_network_image: ^3.4.1
  intl: ^0.20.2

  #YoloV8 Flutter Vision Izzat
  flutter_vision: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/assets/icons/
    - assets/assets/icons/google_logo.png
    - assets/assets/videos/
    - assets/assets/placeholder.png
    - assets/assets/offline_materials/ 
    - assets/assets/models/
    - assets/models/best_float32.tflite 

