name: signlinggo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Flutter packages
  cupertino_icons: ^1.0.8
  video_player: ^2.8.6
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.23
  http: ^1.5.0
  visibility_detector: ^0.4.0+2
  share_plus: ^12.0.1
  scroll_to_index: ^3.0.1
  camera: ^0.11.3
  path_provider: ^2.1.5
  path: ^1.9.1
  record: ^6.1.2
  google_sign_in: ^7.2.0
  firebase_core: ^4.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #video_player: ^2.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/assets/icons/
    - assets/assets/videos/
    - assets/assets/placeholder.png
